[versions]
androidGradlePlugin = "8.1.0"
# AndroidX
androidx-navigation = "2.5.3"
androidx-lifecycle-compose = "2.6.1"
androidx-core-ktx = "1.9.0"
androidx-activity-compose = "1.7.2"
androidx-compose-bom = "2023.03.00"

# TEST
junit = "4.13.2"
androidx-test-core = "1.5.0"
androidx-test-ext-junit = "1.1.5"
androidx-test-espresso = "3.5.1"

# Kotlin
kotlin = "1.8.10"
kotlin-compose-compiler = "1.4.3"
ksp = "1.8.10-1.0.9"
kotlin-coroutine = "1.6.4"

# Room
room = "2.5.0"

# Hilt
hilt = "2.44"


[libraries]
#androidx
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx"}
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-compose"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose"}
androidx-compose-bom = {module = "androidx.compose:compose-bom", version.ref="androidx-compose-bom"}
androidx-compose-ui = { module = "androidx.compose.ui:ui"}
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics"}
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room"}
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room"}
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}

#kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutine" }

#test
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" , version.ref = "kotlin-coroutine" }
junit = { module = "junit:junit",version.ref = "junit"}
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit"}
androidx-test-core = { module = "androidx.test:core", version.ref="androidx-test-core"}
androidx-test-espresso-core = {module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso"}
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
android-library = { id = "com.android.library",  version.ref="androidGradlePlugin"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}

